spring.application.name=service-registry

server.port=8761

# Eureka Server
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Eureka Server dashboard
eureka.server.enable-self-preservation=true

# Management / Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always